In [25]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt

def print_full(x):
    pd.set_option('display.max_rows', len(x))
    f = open('output.txt', 'w')
    print(x)
    print >> f, x
    pd.reset_option('display.max_rows')
    f.close()

data_df = pd.read_csv("speed_dating_train.csv", encoding="ISO-8859-1")
# take a quick look into Data
#print(data_df.head())	
#print(data_df.describe())

# see NaN
#print_full(data_df.isnull().sum())

# delete unwanted columns and wave 6 to 9
nonvars=["iid", "id", "idg", "condtn", "position", "positin1", "partner", "pid", "dec_o", "like_o", "prob_o", "met_o", "field", "undergra", "mn_sat", "tuition", "from", "income", "goal", "date", "go_out", "career", "sports", "tvsports", "exercise", "dining", "museums", "art", "hiking", "gaming", "clubbing", "reading", "tv", "theater", "movies", "concerts", "music", "shopping", "yoga", "exphappy", "expnum", "zipcode", "attr4_1", "sinc4_1", "intel4_1", "fun4_1", "amb4_1", "shar4_1", "attr5_1", "sinc5_1", "intel5_1", "fun5_1", "amb5_1", "dec", "like", "prob", "met", "match_es", "attr1_s", "sinc1_s", "intel1_s", "fun1_s", "amb1_s", "shar1_s", "attr3_s", "sinc3_s", "intel3_s", "fun3_s", "amb3_s", "satis_2", "length", "numdat_2", "attr7_2", "sinc7_2", "intel7_2", "fun7_2", "amb7_2", "shar7_2", "attr1_2", "sinc1_2", "intel1_2", "fun1_2", "amb1_2", "shar1_2", "attr4_2", "sinc4_2", "intel4_2", "fun4_2", "amb4_2", "shar4_2", "attr2_2", "sinc2_2", "intel2_2", "fun2_2", "amb2_2", "shar2_2", "attr3_2", "sinc3_2", "intel3_2", "fun3_2", "amb3_2", "attr5_2", "sinc5_2", "intel5_2", "fun5_2", "amb5_2", "you_call", "them_cal", "date_3", "numdat_3", "num_in_3", "attr1_3", "sinc1_3", "intel1_3", "fun1_3", "amb1_3", "shar1_3", "attr7_3", "sinc7_3", "intel7_3", "fun7_3", "amb7_3", "shar7_3", "attr4_3", "sinc4_3", "intel4_3", "fun4_3", "amb4_3", "shar4_3", "attr2_3", "sinc2_3", "intel2_3", "fun2_3", "amb2_3", "shar2_3", "attr3_3", "sinc3_3", "intel3_3", "fun3_3", "amb3_3", "attr5_3", "sinc5_3", "intel5_3", "fun5_3", "amb5_3"]
df_exclude=data_df.drop(data_df[(data_df.wave>5) & (data_df.wave<10)].index).drop(nonvars, 1)
# delete rows contain NaN
nan_row_index = pd.isnull(df_exclude).any(1).nonzero()[0]
df_clean = df_exclude.drop(df_exclude.index[nan_row_index])

# divide data into train set and test set (wave 21)
exclude_wave21_df = df_clean.drop(df_clean[df_clean.wave==21].index)
match_df = exclude_wave21_df.drop(exclude_wave21_df[exclude_wave21_df.match==0].index)
not_match_df = exclude_wave21_df.drop(exclude_wave21_df[exclude_wave21_df.match==1].index)
train_df = not_match_df.sample(710).append(match_df).drop("wave", 1)

#test_df = df_clean.drop(df_clean[(df_clean.wave<21)].index).drop("wave", 1)

from sklearn.svm import SVC
train_df_X = train_df.drop("match", 1)
train_df_y = train_df.match

a_stt = train_df.columns
print(a_stt)
#data_df[train_df.columns]
#test_df_X = test_df.drop("match", 1)
#test_df_y = test_df.match

Index([u'recordid', u'gender', u'round', u'order', u'match', u'int_corr',
       u'samerace', u'age_o', u'race_o', u'pf_o_att', u'pf_o_sin', u'pf_o_int',
       u'pf_o_fun', u'pf_o_amb', u'pf_o_sha', u'attr_o', u'sinc_o', u'intel_o',
       u'fun_o', u'amb_o', u'shar_o', u'age', u'field_cd', u'race', u'imprace',
       u'imprelig', u'career_c', u'attr1_1', u'sinc1_1', u'intel1_1',
       u'fun1_1', u'amb1_1', u'shar1_1', u'attr2_1', u'sinc2_1', u'intel2_1',
       u'fun2_1', u'amb2_1', u'shar2_1', u'attr3_1', u'sinc3_1', u'fun3_1',
       u'intel3_1', u'amb3_1', u'attr', u'sinc', u'intel', u'fun', u'amb',
       u'shar'],
      dtype='object')

In [32]:
data_df_test = pd.read_csv("speed_dating_test.csv", encoding="ISO-8859-1")
test_df_X = data_df_test[train_df_X.columns]
#test_df_X = test_df.drop("match", 1)
test_df_X.head()

<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>recordid</th>
      <th>gender</th>
      <th>round</th>
      <th>order</th>
      <th>int_corr</th>
      <th>samerace</th>
      <th>age_o</th>
      <th>race_o</th>
      <th>pf_o_att</th>
      <th>pf_o_sin</th>
      <th>...</th>
      <th>sinc3_1</th>
      <th>fun3_1</th>
      <th>intel3_1</th>
      <th>amb3_1</th>
      <th>attr</th>
      <th>sinc</th>
      <th>intel</th>
      <th>fun</th>
      <th>amb</th>
      <th>shar</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>7411</td>
      <td>0</td>
      <td>22</td>
      <td>8</td>
      <td>-0.12</td>
      <td>1</td>
      <td>25</td>
      <td>4</td>
      <td>15</td>
      <td>30</td>
      <td>...</td>
      <td>6</td>
      <td>4</td>
      <td>8</td>
      <td>9</td>
      <td>2</td>
      <td>8</td>
      <td>6</td>
      <td>5</td>
      <td>4</td>
      <td>4</td>
    </tr>
    <tr>
      <th>1</th>
      <td>7412</td>
      <td>0</td>
      <td>22</td>
      <td>5</td>
      <td>0.03</td>
      <td>1</td>
      <td>26</td>
      <td>4</td>
      <td>25</td>
      <td>20</td>
      <td>...</td>
      <td>6</td>
      <td>4</td>
      <td>8</td>
      <td>9</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>2</th>
      <td>7413</td>
      <td>0</td>
      <td>22</td>
      <td>20</td>
      <td>0.37</td>
      <td>0</td>
      <td>26</td>
      <td>2</td>
      <td>25</td>
      <td>25</td>
      <td>...</td>
      <td>6</td>
      <td>4</td>
      <td>8</td>
      <td>9</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>2</td>
      <td>3</td>
      <td>2</td>
    </tr>
    <tr>
      <th>3</th>
      <td>7414</td>
      <td>0</td>
      <td>22</td>
      <td>7</td>
      <td>0.11</td>
      <td>0</td>
      <td>24</td>
      <td>6</td>
      <td>30</td>
      <td>30</td>
      <td>...</td>
      <td>6</td>
      <td>4</td>
      <td>8</td>
      <td>9</td>
      <td>8</td>
      <td>5</td>
      <td>7</td>
      <td>6</td>
      <td>7</td>
      <td>3</td>
    </tr>
    <tr>
      <th>4</th>
      <td>7415</td>
      <td>0</td>
      <td>22</td>
      <td>4</td>
      <td>0.39</td>
      <td>0</td>
      <td>23</td>
      <td>2</td>
      <td>23</td>
      <td>14</td>
      <td>...</td>
      <td>6</td>
      <td>4</td>
      <td>8</td>
      <td>9</td>
      <td>3</td>
      <td>7</td>
      <td>6</td>
      <td>6</td>
      <td>5</td>
      <td>4</td>
    </tr>
  </tbody>
</table>
<p>5 rows Ã— 49 columns</p>
</div>

In [34]:
clf = SVC(kernel='poly', degree=1)
model = clf.fit(train_df_X, train_df_y)

In [56]:
#model.predict(test_df_X)
eeata = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000,None , 2002, 2001, 2002],
        'pop': [1.5, 1.7,None, 2.4, 2.9]}
frame = pd.DataFrame(eeata)
frame['pop'] = frame['pop'].fillna( 3)
frame['pop'].mean()

2.3

In [59]:
for index in train_df_X.columns:
    test_df_X[index]= test_df_X[index].fillna( train_df_X[index].mean())
    pass

result = model.predict(test_df_X)
result

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [73]:
a = data_df_test['recordid']
b=pd.DataFrame({'recordid':a, 'predict':result},columns=['recordid','predict'])
b
b.to_csv("kk.csv",index=False);